version: '3.9'

services:
  upbit-trading:
    build: .
    container_name: upbit-trading
    env_file: .env
    image: upbit-trading:latest
    restart: on-failure
    ports:
      - $PORT:$PORT
    volumes:
      - './docs:/app/docs'
