version: '3.9'

services:
  upbit-trading-app:
    build: .
    container_name: upbit-trading-app
    env_file: .env
    image: upbit-trading-app:latest
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    volumes:
      - './docs:/app/docs'
